[build]
  functions = "netlify/functions"
  publish = "public"

[[functions]]
  directory = "netlify/functions"
  timeout = 10

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
