[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"  # Optionnel, pour spécifier le bundler si vous utilisez des modules externes
  timeout = 10              # Délai d'exécution maximum pour les fonctions serverless

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
